package files;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class Payloads{
	
	public static String addPlace() {
		return "{\r\n"
				+ "  \"location\": {\r\n"
				+ "    \"lat\": -38.383494,\r\n"
				+ "    \"lng\": 33.427362\r\n"
				+ "  },\r\n"
				+ "  \"accuracy\": 50,\r\n"
				+ "  \"name\": \"Frontline house\",\r\n"
				+ "  \"phone_number\": \"(+91) 983 893 3937\",\r\n"
				+ "  \"address\": \"29, side layout, cohen 09\",\r\n"
				+ "  \"types\": [\r\n"
				+ "    \"shoe park\",\r\n"
				+ "    \"shop\"\r\n"
				+ "  ],\r\n"
				+ "  \"website\": \"http://google.com\",\r\n"
				+ "  \"language\": \"French-IN\"\r\n"
				+ "}";
	}
	
	public static String updatePlace(String place_id,String new_address) {
		return "{\r\n"
				+ "\"place_id\":\""+place_id+"\",\r\n"
				+ "\"address\":\""+new_address+"\",\r\n"
				+ "\"key\":\"qaclick123\"\r\n"
				+ "}";
	}
	
	public static String coursePrice() {
		return "{\r\n"
				+ "\r\n"
				+ "\"dashboard\": {\r\n"
				+ "\r\n"
				+ "\"purchaseAmount\": 910,\r\n"
				+ "\r\n"
				+ "\"website\": \"rahulshettyacademy.com\"\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "\"courses\": [\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Selenium Python\",\r\n"
				+ "\r\n"
				+ "\"price\": 50,\r\n"
				+ "\r\n"
				+ "\"copies\": 6\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Cypress\",\r\n"
				+ "\r\n"
				+ "\"price\": 40,\r\n"
				+ "\r\n"
				+ "\"copies\": 4\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"RPA\",\r\n"
				+ "\r\n"
				+ "\"price\": 45,\r\n"
				+ "\r\n"
				+ "\"copies\": 10\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "]\r\n"
				+ "\r\n"
				+ "}";
	}
	

	public static String addBook(String isbn, String aisle) {
		String payload = "{\r\n"
				+ "\r\n"
				+ "\"name\":\"Learn Appium Automation with Java\",\r\n"
				+ "\"isbn\":\""+isbn+"\",\r\n"
				+ "\"aisle\":\""+aisle+"\",\r\n"
				+ "\"author\":\"John foe\"\r\n"
				+ "}\r\n"
				+ "";
		return payload;
	}
	
	public static String createIssue() {
		String payload = "{\r\n"
				+ "    \"fields\": {\r\n"
				+ "        \"project\": {\r\n"
				+ "            \"key\": \"RAAA\"\r\n"
				+ "        },\r\n"
				+ "        \"summary\": \"Rest Assured Defect - 1\",\r\n"
				+ "        \"issuetype\": {\r\n"
				+ "            \"name\": \"Bug\"\r\n"
				+ "        },\r\n"
				+ "        \"description\": \"First Rest Assured Defect\"\r\n"
				+ "    }\r\n"
				+ "}";
		return payload;
	}
	
	public static String addComment(String comment) {
		String payload = "{\r\n"
				+ "    \"body\": \""+comment+"\",\r\n"
				+ "    \"visibility\": {\r\n"
				+ "        \"type\": \"role\",\r\n"
				+ "        \"value\": \"Administrators\"\r\n"
				+ "    }\r\n"
				+ "}";
		return payload;
	}
	
	public static Map<String, Object> addCommentMap(String comment) {
		Map<String,Object> map = new HashMap<String,Object>();
		map.put("body", comment);
		map.put("visibility", Arrays.asList("type","Role"));
		map.put("visibility", Arrays.asList("value","Administrators"));
		return map;
	}
	
	public static Map<String, Object> addBookHashMap() throws IOException {
		
		ArrayList<String> data=Common.getDataFromExcel("D:\\testdata.xlsx", "data", "TestCase", "AddBook");
		HashMap<String,Object> map = new HashMap<String,Object>();
		map.put("name", data.get(1));
		map.put("isbn", data.get(2));
		map.put("aisle", data.get(3));
		map.put("author", data.get(4));
		return map;
		
	}
	
	public static String getIssue() {
		String payload="{\r\n"
				+ "    \"expand\": \"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations\",\r\n"
				+ "    \"id\": \"10002\",\r\n"
				+ "    \"self\": \"http://localhost:8080/rest/api/2/issue/10002\",\r\n"
				+ "    \"key\": \"RAAA-3\",\r\n"
				+ "    \"fields\": {\r\n"
				+ "        \"comment\": {\r\n"
				+ "            \"comments\": [\r\n"
				+ "                {\r\n"
				+ "                    \"self\": \"http://localhost:8080/rest/api/2/issue/10002/comment/10001\",\r\n"
				+ "                    \"id\": \"10001\",\r\n"
				+ "                    \"author\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"body\": \"Adding a comment in an issue.\",\r\n"
				+ "                    \"updateAuthor\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"created\": \"2021-07-01T08:52:54.350+0530\",\r\n"
				+ "                    \"updated\": \"2021-07-01T08:52:54.350+0530\",\r\n"
				+ "                    \"visibility\": {\r\n"
				+ "                        \"type\": \"role\",\r\n"
				+ "                        \"value\": \"Administrators\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"self\": \"http://localhost:8080/rest/api/2/issue/10002/comment/10002\",\r\n"
				+ "                    \"id\": \"10002\",\r\n"
				+ "                    \"author\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"body\": \"Adding a comment in an issue.\",\r\n"
				+ "                    \"updateAuthor\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"created\": \"2021-07-01T09:55:57.862+0530\",\r\n"
				+ "                    \"updated\": \"2021-07-01T09:55:57.862+0530\",\r\n"
				+ "                    \"visibility\": {\r\n"
				+ "                        \"type\": \"role\",\r\n"
				+ "                        \"value\": \"Administrators\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"self\": \"http://localhost:8080/rest/api/2/issue/10002/comment/10003\",\r\n"
				+ "                    \"id\": \"10003\",\r\n"
				+ "                    \"author\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"body\": \"Adding a comment in an issue.\",\r\n"
				+ "                    \"updateAuthor\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"created\": \"2021-07-01T09:56:04.890+0530\",\r\n"
				+ "                    \"updated\": \"2021-07-01T09:56:04.890+0530\",\r\n"
				+ "                    \"visibility\": {\r\n"
				+ "                        \"type\": \"role\",\r\n"
				+ "                        \"value\": \"Administrators\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"self\": \"http://localhost:8080/rest/api/2/issue/10002/comment/10004\",\r\n"
				+ "                    \"id\": \"10004\",\r\n"
				+ "                    \"author\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"body\": \"Adding a comment in an issue.\",\r\n"
				+ "                    \"updateAuthor\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=saurabh.r.gupta\",\r\n"
				+ "                        \"name\": \"saurabh.r.gupta\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/0c14ed42caf6501c6677043fa5a2c965?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"saurabh.r.gupta@impetus.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"Asia/Calcutta\"\r\n"
				+ "                    },\r\n"
				+ "                    \"created\": \"2021-07-01T09:56:09.268+0530\",\r\n"
				+ "                    \"updated\": \"2021-07-01T09:56:09.268+0530\",\r\n"
				+ "                    \"visibility\": {\r\n"
				+ "                        \"type\": \"role\",\r\n"
				+ "                        \"value\": \"Administrators\"\r\n"
				+ "                    }\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"maxResults\": 4,\r\n"
				+ "            \"total\": 4,\r\n"
				+ "            \"startAt\": 0\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "}";
		return payload;
	}
}
